---Optimization and Graphics
NDefines.NGame.DAYS_BEHIND_PAUSE = 90
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 55
NDefines.NEngine.EVENT_PROCESS_OFFSET = 55
NDefines.NGraphics.CAPITAL_INDICATOR_HEIGHT_SCALE = 100.0
NDefines.NGraphics.CAPITAL_INDICATOR_HEIGHT = 0
NDefines.NGraphics.BORDER_WIDTH = 1
NDefines.NGraphics.DIRECTION_POINTER_DRAW_DISTANCE = 1000
NDefines.NGraphics.DIRECTION_POINTER_INTERPOLATION_SPEED = 0.1

--- AI
NDefines.NAI.DEVELOPMENT_CAP_BASE = 30

--- Diplo
NDefines.NDiplomacy.PO_FORM_PU_AE = 0.05
NDefines.NDiplomacy.IMPERIAL_AUTHORITY_FROM_PRINCES = 0.075
NDefines.NDiplomacy.IMPERIAL_CITY_IA = 0.008 
NDefines.NDiplomacy.IMPERIAL_REFORM_COST = 40
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.CONDOTTIERI_MIN_DURATION = 1
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10
NDefines.NDiplomacy.HRE_AUTHORITY_JOIN_EMPIRE = 0
NDefines.NDiplomacy.GREAT_POWER_SUBJECT_CONTRIBUTION = 0
NDefines.NDiplomacy.NUM_OF_GREAT_POWERS = 10

---Country
NDefines.NCountry.MONARCH_MIN_SKILL = 1
NDefines.NCountry.NAT_FOCUS_YEARS = 20
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 120
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -50
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -30
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -30
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.EXPLOIT_COOLDOWN_MONTHS = 120

--NMilitary
NDefines.NMilitary.WARGOAL_MAX_BONUS = 50
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 10
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0

-- Economy
NDefines.NEconomy.CARAVAN_POWER_MAX = 4
NDefines.NEconomy.CARAVAN_POWER_MIN = 1